"""Per-role weight distributions for the 14 scoring dimensions. Weights sum to 1.0."""

from __future__ import annotations

ROLE_PROFILES: dict[str, dict[str, float]] = {
    "software_engineer_backend": {
        "keyword_density": 0.12,
        "skill_depth": 0.12,
        "tech_stack_alignment": 0.15,
        "experience_relevance": 0.12,
        "quantified_impact": 0.08,
        "action_verb_strength": 0.05,
        "section_ordering": 0.04,
        "bullet_quality": 0.07,
        "ats_parsability": 0.06,
        "seniority_calibration": 0.08,
        "domain_knowledge": 0.04,
        "education_relevance": 0.03,
        "semantic_similarity": 0.03,
        "voice_alignment": 0.01,
    },
    "software_engineer_frontend": {
        "keyword_density": 0.10,
        "skill_depth": 0.10,
        "tech_stack_alignment": 0.18,
        "experience_relevance": 0.10,
        "quantified_impact": 0.06,
        "action_verb_strength": 0.04,
        "section_ordering": 0.04,
        "bullet_quality": 0.08,
        "ats_parsability": 0.06,
        "seniority_calibration": 0.08,
        "domain_knowledge": 0.05,
        "education_relevance": 0.03,
        "semantic_similarity": 0.06,
        "voice_alignment": 0.02,
    },
    "ml_engineer": {
        "keyword_density": 0.10,
        "skill_depth": 0.13,
        "tech_stack_alignment": 0.12,
        "experience_relevance": 0.13,
        "quantified_impact": 0.10,
        "action_verb_strength": 0.04,
        "section_ordering": 0.05,
        "bullet_quality": 0.06,
        "ats_parsability": 0.04,
        "seniority_calibration": 0.07,
        "domain_knowledge": 0.07,
        "education_relevance": 0.05,
        "semantic_similarity": 0.03,
        "voice_alignment": 0.01,
    },
    "product_manager": {
        "keyword_density": 0.08,
        "skill_depth": 0.08,
        "tech_stack_alignment": 0.04,
        "experience_relevance": 0.14,
        "quantified_impact": 0.14,
        "action_verb_strength": 0.07,
        "section_ordering": 0.05,
        "bullet_quality": 0.09,
        "ats_parsability": 0.05,
        "seniority_calibration": 0.09,
        "domain_knowledge": 0.09,
        "education_relevance": 0.04,
        "semantic_similarity": 0.03,
        "voice_alignment": 0.01,
    },
    "data_scientist": {
        "keyword_density": 0.09,
        "skill_depth": 0.11,
        "tech_stack_alignment": 0.11,
        "experience_relevance": 0.12,
        "quantified_impact": 0.12,
        "action_verb_strength": 0.04,
        "section_ordering": 0.04,
        "bullet_quality": 0.06,
        "ats_parsability": 0.04,
        "seniority_calibration": 0.07,
        "domain_knowledge": 0.08,
        "education_relevance": 0.07,
        "semantic_similarity": 0.04,
        "voice_alignment": 0.01,
    },
    "devops_sre": {
        "keyword_density": 0.11,
        "skill_depth": 0.11,
        "tech_stack_alignment": 0.18,
        "experience_relevance": 0.11,
        "quantified_impact": 0.09,
        "action_verb_strength": 0.05,
        "section_ordering": 0.04,
        "bullet_quality": 0.07,
        "ats_parsability": 0.05,
        "seniority_calibration": 0.07,
        "domain_knowledge": 0.05,
        "education_relevance": 0.02,
        "semantic_similarity": 0.04,
        "voice_alignment": 0.01,
    },
    "research_scientist": {
        "keyword_density": 0.07,
        "skill_depth": 0.09,
        "tech_stack_alignment": 0.07,
        "experience_relevance": 0.10,
        "quantified_impact": 0.07,
        "action_verb_strength": 0.03,
        "section_ordering": 0.05,
        "bullet_quality": 0.05,
        "ats_parsability": 0.04,
        "seniority_calibration": 0.08,
        "domain_knowledge": 0.10,
        "education_relevance": 0.14,
        "semantic_similarity": 0.09,
        "voice_alignment": 0.02,
    },
    "design_ux": {
        "keyword_density": 0.08,
        "skill_depth": 0.10,
        "tech_stack_alignment": 0.10,
        "experience_relevance": 0.13,
        "quantified_impact": 0.08,
        "action_verb_strength": 0.06,
        "section_ordering": 0.05,
        "bullet_quality": 0.09,
        "ats_parsability": 0.05,
        "seniority_calibration": 0.08,
        "domain_knowledge": 0.07,
        "education_relevance": 0.03,
        "semantic_similarity": 0.05,
        "voice_alignment": 0.03,
    },
}


def get_role_profile(role_type: str) -> dict[str, float]:
    return ROLE_PROFILES.get(role_type, _get_generic_profile())


def _get_generic_profile() -> dict[str, float]:
    n = len(ROLE_PROFILES["software_engineer_backend"])
    base = ROLE_PROFILES["software_engineer_backend"]
    return {k: round(1.0 / n, 4) for k in base}
