"""Seniority-based weight adjustments applied on top of role profiles."""

from __future__ import annotations

SENIORITY_MULTIPLIERS: dict[str, dict[str, float]] = {
    "intern": {
        "keyword_density": 1.1,
        "skill_depth": 0.9,
        "tech_stack_alignment": 1.0,
        "experience_relevance": 0.5,
        "quantified_impact": 0.5,
        "action_verb_strength": 0.8,
        "section_ordering": 1.0,
        "bullet_quality": 1.0,
        "ats_parsability": 1.0,
        "seniority_calibration": 0.7,
        "domain_knowledge": 0.6,
        "education_relevance": 1.8,
        "semantic_similarity": 1.0,
        "voice_alignment": 0.5,
    },
    "junior": {
        "keyword_density": 1.1,
        "skill_depth": 1.0,
        "tech_stack_alignment": 1.1,
        "experience_relevance": 0.8,
        "quantified_impact": 0.7,
        "action_verb_strength": 0.9,
        "section_ordering": 1.0,
        "bullet_quality": 1.0,
        "ats_parsability": 1.0,
        "seniority_calibration": 0.9,
        "domain_knowledge": 0.7,
        "education_relevance": 1.4,
        "semantic_similarity": 1.0,
        "voice_alignment": 0.8,
    },
    "mid": {
        "keyword_density": 1.0,
        "skill_depth": 1.0,
        "tech_stack_alignment": 1.0,
        "experience_relevance": 1.0,
        "quantified_impact": 1.0,
        "action_verb_strength": 1.0,
        "section_ordering": 1.0,
        "bullet_quality": 1.0,
        "ats_parsability": 1.0,
        "seniority_calibration": 1.0,
        "domain_knowledge": 1.0,
        "education_relevance": 1.0,
        "semantic_similarity": 1.0,
        "voice_alignment": 1.0,
    },
    "senior": {
        "keyword_density": 0.9,
        "skill_depth": 1.2,
        "tech_stack_alignment": 1.0,
        "experience_relevance": 1.3,
        "quantified_impact": 1.4,
        "action_verb_strength": 1.2,
        "section_ordering": 1.0,
        "bullet_quality": 1.1,
        "ats_parsability": 1.0,
        "seniority_calibration": 1.2,
        "domain_knowledge": 1.1,
        "education_relevance": 0.6,
        "semantic_similarity": 1.0,
        "voice_alignment": 1.1,
    },
    "staff_principal": {
        "keyword_density": 0.7,
        "skill_depth": 1.3,
        "tech_stack_alignment": 0.9,
        "experience_relevance": 1.4,
        "quantified_impact": 1.5,
        "action_verb_strength": 1.4,
        "section_ordering": 1.0,
        "bullet_quality": 1.1,
        "ats_parsability": 1.0,
        "seniority_calibration": 1.3,
        "domain_knowledge": 1.3,
        "education_relevance": 0.4,
        "semantic_similarity": 1.0,
        "voice_alignment": 1.3,
    },
    "executive": {
        "keyword_density": 0.5,
        "skill_depth": 1.0,
        "tech_stack_alignment": 0.5,
        "experience_relevance": 1.2,
        "quantified_impact": 1.8,
        "action_verb_strength": 1.5,
        "section_ordering": 1.0,
        "bullet_quality": 1.0,
        "ats_parsability": 0.8,
        "seniority_calibration": 1.4,
        "domain_knowledge": 1.4,
        "education_relevance": 0.3,
        "semantic_similarity": 0.8,
        "voice_alignment": 1.5,
    },
}


def apply_seniority_adjustment(
    base_weights: dict[str, float],
    seniority: str,
) -> dict[str, float]:
    multipliers = SENIORITY_MULTIPLIERS.get(seniority, SENIORITY_MULTIPLIERS["mid"])
    adjusted = {k: base_weights[k] * multipliers[k] for k in base_weights}
    total = sum(adjusted.values())
    return {k: v / total for k, v in adjusted.items()}
