"""
Exportable Proof Artifacts — generates branded HTML/PDF reports.

4 report types:
  1. Score Report (22-dim dual score + callback + optional salary)
  2. Tailor Diff Report (before/after + change log)
  3. Coaching Report (session summary + per-question grades)
  4. Analytics Snapshot (funnel + trends + predictions)

Uses weasyprint for PDF if available, otherwise returns styled HTML.
"""

from __future__ import annotations

from datetime import datetime, UTC
from typing import Optional

# Check weasyprint availability
_WEASYPRINT_AVAILABLE = False
try:
    import weasyprint  # type: ignore
    _WEASYPRINT_AVAILABLE = True
except (ImportError, OSError):
    pass


def is_pdf_available() -> bool:
    return _WEASYPRINT_AVAILABLE


def _html_to_output(html: str) -> tuple[bytes, str]:
    """Convert HTML to PDF bytes if possible, otherwise return HTML bytes."""
    if _WEASYPRINT_AVAILABLE:
        pdf_bytes = weasyprint.HTML(string=html).write_pdf()
        return pdf_bytes, "application/pdf"
    return html.encode("utf-8"), "text/html"


# ── Shared CSS ───────────────────────────────────────────────────────────────

_BASE_CSS = """
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        color: #e2e8f0; background: #0f172a; line-height: 1.6; padding: 40px;
    }
    .header { text-align: center; margin-bottom: 32px; padding-bottom: 20px;
              border-bottom: 2px solid #f59e0b; }
    .header h1 { font-size: 28px; font-weight: 800; color: #ffffff; }
    .header .brand { color: #f59e0b; }
    .header .subtitle { font-size: 14px; color: #94a3b8; margin-top: 4px; }
    .section { margin: 28px 0; }
    .section h2 { font-size: 18px; font-weight: 700; color: #f59e0b;
                  text-transform: uppercase; letter-spacing: 1px; margin-bottom: 12px;
                  padding-bottom: 6px; border-bottom: 1px solid #1e293b; }
    .card { background: #1e293b; border-radius: 8px; padding: 20px; margin: 12px 0; }
    .score-big { font-size: 48px; font-weight: 900; color: #f59e0b; text-align: center; }
    .score-label { font-size: 12px; color: #94a3b8; text-align: center;
                   text-transform: uppercase; letter-spacing: 1px; }
    .score-row { display: flex; justify-content: space-around; text-align: center; }
    .score-box { flex: 1; }
    table { width: 100%; border-collapse: collapse; margin: 8px 0; }
    th { background: #1e293b; color: #f59e0b; text-align: left; padding: 10px 12px;
         font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
    td { padding: 8px 12px; border-bottom: 1px solid #1e293b; font-size: 13px; }
    tr:nth-child(even) { background: rgba(30, 41, 59, 0.3); }
    .green { color: #34d399; } .amber { color: #fbbf24; } .red { color: #f87171; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px;
             font-size: 10px; font-weight: 700; text-transform: uppercase; }
    .badge-green { background: rgba(52,211,153,0.15); color: #34d399; }
    .badge-amber { background: rgba(251,191,36,0.15); color: #fbbf24; }
    .badge-red { background: rgba(248,113,113,0.15); color: #f87171; }
    .list-item { padding: 4px 0; font-size: 13px; }
    .list-item .icon { margin-right: 6px; }
    .footer { text-align: center; margin-top: 40px; padding-top: 16px;
              border-top: 1px solid #1e293b; font-size: 11px; color: #475569; }
    .highlight { background: rgba(251,191,36,0.1); padding: 12px; border-radius: 6px;
                 border-left: 3px solid #f59e0b; margin: 12px 0; }
"""


def _score_color(score: float) -> str:
    if score >= 70:
        return "green"
    if score >= 40:
        return "amber"
    return "red"


def _score_badge(score: float) -> str:
    cls = _score_color(score)
    return f'<span class="badge badge-{cls}">{score:.0f}</span>'


def _priority_badge(priority: str) -> str:
    colors = {"critical": "red", "high": "amber", "medium": "amber", "low": "green"}
    cls = colors.get(priority, "amber")
    return f'<span class="badge badge-{cls}">{priority}</span>'


def _header(title: str, subtitle: str = "") -> str:
    now = datetime.now(UTC).strftime("%B %d, %Y")
    sub = f'<div class="subtitle">{subtitle} | {now}</div>' if subtitle else f'<div class="subtitle">{now}</div>'
    return f"""
    <div class="header">
        <h1>Land <span class="brand">It</span> — {title}</h1>
        {sub}
    </div>
    """


def _footer() -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    return f'<div class="footer">Generated by Land It | {now}</div>'


def _wrap_html(body: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>Land It Report</title>
<style>{_BASE_CSS}</style></head><body>{body}{_footer()}</body></html>"""


# ── Report Type 1: Score Report ──────────────────────────────────────────────

def generate_score_report(
    dual_result,
    resume,
    jd,
    salary=None,
) -> tuple[bytes, str]:
    """Generate a 22-dimension score report."""
    ats = dual_result.ats
    standout = dual_result.standout
    cb = dual_result.callback_prediction

    name = resume.contact.name if resume.contact else "Candidate"
    role = jd.title or "Target Role"
    company = jd.company or "Target Company"

    # Score summary
    scores_html = f"""
    <div class="section">
        <div class="score-row">
            <div class="score-box">
                <div class="score-big">{ats.total_score:.0f}</div>
                <div class="score-label">ATS Score ({ats.letter_grade})</div>
            </div>
            <div class="score-box">
                <div class="score-big">{standout.total_score:.0f}</div>
                <div class="score-label">Standout Score</div>
            </div>
            <div class="score-box">
                <div class="score-big" style="color:#ffffff">{dual_result.combined_score}</div>
                <div class="score-label">Combined ({dual_result.combined_grade})</div>
            </div>
        </div>
    </div>
    """

    # Callback
    cb_html = ""
    if cb:
        ci_low, ci_high = cb.confidence_interval
        cb_html = f"""
        <div class="highlight">
            <strong>Callback Probability:</strong> {cb.probability:.0%}
            (confidence interval: {ci_low:.0%} – {ci_high:.0%}, {cb.confidence_level} confidence)
        </div>
        """

    # Dimension table
    all_dims = list(ats.dimension_scores) + list(standout.dimension_scores)
    all_dims.sort(key=lambda d: {"critical": 0, "high": 1, "medium": 2, "low": 3}.get(d.priority, 4))

    rows = ""
    for d in all_dims:
        color = _score_color(d.raw_score)
        rows += f"""<tr>
            <td>{d.dimension_name}</td>
            <td class="{color}">{d.raw_score:.0f}</td>
            <td>{d.weight:.0%}</td>
            <td>{d.weighted_score:.1f}</td>
            <td>{_priority_badge(d.priority)}</td>
        </tr>"""

    dim_table = f"""
    <div class="section">
        <h2>Dimension Breakdown (22 Dimensions)</h2>
        <table>
            <thead><tr><th>Dimension</th><th>Score</th><th>Weight</th><th>Weighted</th><th>Priority</th></tr></thead>
            <tbody>{rows}</tbody>
        </table>
    </div>
    """

    # Strengths + Improvements
    strengths = "".join(
        f'<div class="list-item"><span class="icon green">+</span> {w}</div>'
        for w in (ats.top_3_wins + standout.top_3_wins)[:4]
    )
    issues = "".join(
        f'<div class="list-item"><span class="icon red">!</span> {i}</div>'
        for i in (ats.top_3_issues + standout.top_3_issues)[:4]
    )

    feedback_html = f"""
    <div class="section">
        <h2>Strengths</h2>
        <div class="card">{strengths}</div>
    </div>
    <div class="section">
        <h2>Areas to Improve</h2>
        <div class="card">{issues}</div>
    </div>
    """

    # Salary section (optional)
    salary_html = ""
    if salary:
        low, high = salary.estimated_range
        salary_html = f"""
        <div class="section">
            <h2>Salary Intelligence</h2>
            <div class="card">
                <div style="text-align:center">
                    <div style="font-size:24px;font-weight:800;color:#f59e0b">
                        ${salary.user_estimated_value:,}
                    </div>
                    <div class="score-label">Your Estimated Market Value</div>
                    <div style="margin-top:8px;font-size:13px;color:#94a3b8">
                        Range: ${low:,} – ${high:,} | Position: {salary.user_position_in_range.replace('_', ' ')}
                    </div>
                </div>
            </div>
        </div>
        """

    body = (
        _header("Score Report", f"{name} — {role} at {company}")
        + scores_html + cb_html + dim_table + feedback_html + salary_html
    )

    return _html_to_output(_wrap_html(body))


# ── Report Type 2: Tailor Diff Report ────────────────────────────────────────

def generate_diff_report(
    original_resume: str,
    tailored_resume: str,
    change_log: list,
    score_before: float,
    score_after: float,
) -> tuple[bytes, str]:
    """Generate a tailoring diff report."""
    improvement = score_after - score_before

    score_html = f"""
    <div class="section">
        <div class="score-row">
            <div class="score-box">
                <div class="score-big" style="font-size:36px">{score_before:.0f}</div>
                <div class="score-label">Before</div>
            </div>
            <div class="score-box">
                <div style="font-size:36px;text-align:center;color:#94a3b8;padding-top:10px">&#8594;</div>
            </div>
            <div class="score-box">
                <div class="score-big" style="font-size:36px">{score_after:.0f}</div>
                <div class="score-label">After</div>
            </div>
            <div class="score-box">
                <div class="score-big green" style="font-size:36px">+{improvement:.0f}</div>
                <div class="score-label">Improvement</div>
            </div>
        </div>
    </div>
    """

    # Change log table
    rows = ""
    for i, c in enumerate(change_log):
        section = getattr(c, "section", c.get("section", "")) if isinstance(c, dict) else c.section
        original = getattr(c, "original", c.get("original", "")) if isinstance(c, dict) else c.original
        rewritten = getattr(c, "rewritten", c.get("rewritten", "")) if isinstance(c, dict) else c.rewritten
        reason = getattr(c, "reason", c.get("reason", "")) if isinstance(c, dict) else c.reason
        requires_v = getattr(c, "requires_verification", c.get("requires_verification", False)) if isinstance(c, dict) else c.requires_verification

        verify_badge = '<span class="badge badge-amber">VERIFY</span>' if requires_v else ""
        rows += f"""<tr>
            <td>{i+1}</td>
            <td>{section}</td>
            <td style="font-size:12px">{original[:120]}...</td>
            <td style="font-size:12px">{rewritten[:120]}...</td>
            <td>{reason} {verify_badge}</td>
        </tr>"""

    change_html = f"""
    <div class="section">
        <h2>Change Log ({len(change_log)} changes)</h2>
        <table>
            <thead><tr><th>#</th><th>Section</th><th>Original</th><th>New</th><th>Reason</th></tr></thead>
            <tbody>{rows}</tbody>
        </table>
    </div>
    """

    body = _header("Resume Tailoring Report") + score_html + change_html
    return _html_to_output(_wrap_html(body))


# ── Report Type 3: Coaching Report ───────────────────────────────────────────

def generate_coaching_report(session_summary: dict) -> tuple[bytes, str]:
    """Generate a mock interview coaching report."""
    session_id = session_summary.get("session_id", "unknown")
    score_pct = session_summary.get("score_pct", 0)
    grade = session_summary.get("grade_letter", "N/A")
    answered = session_summary.get("questions_answered", 0)
    skipped = session_summary.get("questions_skipped", 0)
    total = session_summary.get("total_questions", 0)
    strongest = session_summary.get("strongest_dimension", "")
    weakest = session_summary.get("weakest_dimension", "")
    strengths = session_summary.get("all_strengths", [])
    improvements = session_summary.get("all_improvements", [])
    duration = session_summary.get("duration_seconds", 0)

    overview = f"""
    <div class="section">
        <div class="score-row">
            <div class="score-box">
                <div class="score-big">{score_pct:.0f}%</div>
                <div class="score-label">Session Score ({grade})</div>
            </div>
            <div class="score-box">
                <div class="score-big" style="font-size:36px;color:#ffffff">{answered}/{total}</div>
                <div class="score-label">Answered ({skipped} skipped)</div>
            </div>
            <div class="score-box">
                <div class="score-big" style="font-size:36px;color:#ffffff">{duration/60:.0f}m</div>
                <div class="score-label">Duration</div>
            </div>
        </div>
    </div>
    """

    dim_html = f"""
    <div class="highlight">
        <strong>Strongest:</strong> {strongest} &nbsp;|&nbsp;
        <strong>Weakest:</strong> {weakest}
    </div>
    """

    # Per-question grades (answer text REDACTED for privacy)
    results = session_summary.get("results", [])
    q_rows = ""
    for i, r in enumerate(results):
        q_text = r.get("question_text", f"Question {i+1}")
        score = r.get("score", 0)
        q_strengths = ", ".join(r.get("strengths", [])[:2])
        q_gaps = ", ".join(r.get("improvements", [])[:2])
        q_rows += f"""<tr>
            <td>{i+1}</td>
            <td>{q_text[:100]}</td>
            <td>{_score_badge(score)}</td>
            <td style="font-size:12px">{q_strengths}</td>
            <td style="font-size:12px">{q_gaps}</td>
        </tr>"""

    questions_html = ""
    if q_rows:
        questions_html = f"""
        <div class="section">
            <h2>Per-Question Breakdown</h2>
            <table>
                <thead><tr><th>#</th><th>Question</th><th>Score</th><th>Strengths</th><th>Gaps</th></tr></thead>
                <tbody>{q_rows}</tbody>
            </table>
        </div>
        """

    # Recommendations
    recs = "".join(
        f'<div class="list-item"><span class="icon amber">!</span> {imp}</div>'
        for imp in improvements[:3]
    )
    rec_html = f"""
    <div class="section">
        <h2>Recommendations</h2>
        <div class="card">{recs if recs else '<div class="list-item">Keep up the strong performance!</div>'}</div>
    </div>
    """

    body = _header("Mock Interview Report", f"Session {session_id[:8]}") + overview + dim_html + questions_html + rec_html
    return _html_to_output(_wrap_html(body))


# ── Report Type 4: Analytics Snapshot ────────────────────────────────────────

def generate_analytics_report(analytics) -> tuple[bytes, str]:
    """Generate a job search analytics snapshot report."""
    f = analytics.funnel

    funnel_html = f"""
    <div class="section">
        <h2>Application Funnel</h2>
        <div class="card">
            <div style="font-size:14px;text-align:center">
                Discovered ({f.jobs_discovered})
                &nbsp;&#8594;&nbsp;
                Applied ({f.jobs_applied})
                &nbsp;&#8594;&nbsp;
                Response ({f.responses_received})
                &nbsp;&#8594;&nbsp;
                Interview ({f.interviews_scheduled})
                &nbsp;&#8594;&nbsp;
                Offer ({f.offers_received})
            </div>
            <table style="margin-top:12px">
                <thead><tr><th>Conversion</th><th>Rate</th><th>vs Benchmark</th></tr></thead>
                <tbody>
    """
    for key in ("applied_to_response", "response_to_interview", "interview_to_offer"):
        rate = f.conversion_rates.get(key, 0)
        bench = f.benchmark_comparisons.get(key, "")
        label = key.replace("_", " ").title()
        funnel_html += f"<tr><td>{label}</td><td>{rate:.0%}</td><td>{bench}</td></tr>"

    funnel_html += "</tbody></table></div></div>"

    # Score trends
    trend_text = "improving" if analytics.is_improving else "stable"
    trend_html = f"""
    <div class="section">
        <h2>Score Trends</h2>
        <div class="highlight">
            Scores are <strong>{trend_text}</strong>.
            Change: <strong>{analytics.score_improvement:+.1f}</strong> points since start.
        </div>
    </div>
    """

    # Dimension heatmap
    heatmap = analytics.dimension_heatmap
    heatmap_rows = ""
    for dim_id in heatmap.weakest_dimensions + heatmap.strongest_dimensions:
        avg = heatmap.dimension_averages.get(dim_id, 0)
        name = dim_id.replace("_", " ").title()
        color = _score_color(avg)
        heatmap_rows += f"<tr><td>{name}</td><td class='{color}'>{avg:.0f}</td></tr>"

    heatmap_html = f"""
    <div class="section">
        <h2>Dimension Focus</h2>
        <table><thead><tr><th>Dimension</th><th>Avg Score</th></tr></thead>
        <tbody>{heatmap_rows}</tbody></table>
    </div>
    """ if heatmap_rows else ""

    # Predictions
    preds = analytics.predictions
    pred_html = f"""
    <div class="section">
        <h2>Predictions</h2>
        <div class="card">
            <div style="font-size:14px">
                Estimated weeks to offer: <strong>{preds.estimated_weeks_to_offer:.1f}</strong><br>
                Recommended weekly volume: <strong>{preds.recommended_weekly_volume}</strong> apps/week<br>
                Trajectory: <strong>{preds.current_trajectory.replace('_', ' ')}</strong>
            </div>
        </div>
    </div>
    """

    # Focus areas
    focus_items = "".join(
        f'<div class="list-item"><span class="icon amber">!</span> {a}</div>'
        for a in analytics.focus_areas
    )
    focus_html = f"""
    <div class="section">
        <h2>Action Items</h2>
        <div class="card">{focus_items}</div>
    </div>
    """

    body = (
        _header("Job Search Analytics")
        + f'<div class="highlight" style="text-align:center">{analytics.one_sentence_summary}</div>'
        + funnel_html + trend_html + heatmap_html + pred_html + focus_html
    )
    return _html_to_output(_wrap_html(body))
