export interface DemoApplication {
  id: string;
  company: string;
  role: string;
  status: "Discovered" | "Tailored" | "Applied" | "Interviewing" | "Closed";
  fitScore: number;
  callbackPct: number;
  lastActivity: string;
  logoInitial: string;
  jd: string;
  resumeSample: string;
  heatmap: Array<{ name: string; score: number; type: "ats" | "standout" }>;
}

export const DEMO_APPLICATIONS: DemoApplication[] = [
  {
    id: "app-1",
    company: "Stripe",
    role: "Senior Software Engineer",
    status: "Interviewing",
    fitScore: 84,
    callbackPct: 73,
    lastActivity: "2h ago",
    logoInitial: "S",
    jd: `We are looking for a Senior Software Engineer to join our Payments Infrastructure team. You will build the systems that move money reliably at global scale.\n\nResponsibilities:\n- Design and implement distributed payment systems\n- Build APIs consumed by millions of developers\n- Collaborate with product and design on user-facing features\n\nRequirements:\n- 5+ years of software engineering experience\n- Proficiency in Go, Ruby, or TypeScript\n- Experience with distributed systems and databases\n- Strong system design fundamentals`,
    resumeSample: `Mohammed Haarez — Senior Software Engineer\n\nEXPERIENCE\n\nSoftware Engineer II — Acme Corp (2021–Present)\n• Designed and shipped a distributed job scheduling system handling 2M events/day\n• Reduced p99 API latency by 40% through query optimization and caching layers\n• Led migration of 3 legacy services to TypeScript with zero downtime\n\nSoftware Engineer — StartupXYZ (2019–2021)\n• Built real-time data pipeline processing 500K records/hour\n• Implemented OAuth 2.0 authentication across 5 product surfaces\n\nSKILLS\nTypeScript, Go, PostgreSQL, Redis, Kafka, Kubernetes, AWS`,
    heatmap: [
      { name: "Keyword Match", score: 88, type: "ats" },
      { name: "Skills Alignment", score: 91, type: "ats" },
      { name: "Experience Level", score: 80, type: "ats" },
      { name: "Education Match", score: 75, type: "ats" },
      { name: "Title Match", score: 85, type: "ats" },
      { name: "Recency", score: 90, type: "ats" },
      { name: "Formatting", score: 95, type: "ats" },
      { name: "Length", score: 88, type: "ats" },
      { name: "Action Verbs", score: 82, type: "ats" },
      { name: "Quantification", score: 79, type: "ats" },
      { name: "Tech Stack", score: 86, type: "ats" },
      { name: "Responsibilities", score: 77, type: "ats" },
      { name: "Certifications", score: 60, type: "ats" },
      { name: "Location", score: 95, type: "ats" },
      { name: "Impact Stories", score: 83, type: "standout" },
      { name: "Uniqueness", score: 71, type: "standout" },
      { name: "Voice Match", score: 78, type: "standout" },
      { name: "Culture Fit", score: 80, type: "standout" },
      { name: "Leadership", score: 68, type: "standout" },
      { name: "Spike Signal", score: 72, type: "standout" },
      { name: "Project Depth", score: 85, type: "standout" },
      { name: "Online Presence", score: 65, type: "standout" },
    ],
  },
  {
    id: "app-2",
    company: "Vercel",
    role: "Staff Frontend Engineer",
    status: "Applied",
    fitScore: 78,
    callbackPct: 58,
    lastActivity: "1d ago",
    logoInitial: "V",
    jd: `Join Vercel to build the future of web deployment. We are looking for a Staff Frontend Engineer to own our dashboard and developer experience.\n\nRequirements:\n- 7+ years of experience in frontend engineering\n- Expert-level React and TypeScript\n- Experience with Next.js, Edge functions, and CDN infrastructure\n- Strong opinions on performance and UX`,
    resumeSample: `Mohammed Haarez — Frontend Engineer\n\nEXPERIENCE\n\nFrontend Engineer — Acme Corp (2021–Present)\n• Built React component library used across 6 products, reducing dev time by 30%\n• Shipped Next.js migration cutting LCP by 2.1s across all pages\n• Owned WebSocket real-time collaboration features for 50K daily active users`,
    heatmap: [
      { name: "Keyword Match", score: 80, type: "ats" },
      { name: "Skills Alignment", score: 85, type: "ats" },
      { name: "Experience Level", score: 70, type: "ats" },
      { name: "Education Match", score: 75, type: "ats" },
      { name: "Title Match", score: 72, type: "ats" },
      { name: "Recency", score: 88, type: "ats" },
      { name: "Formatting", score: 92, type: "ats" },
      { name: "Length", score: 85, type: "ats" },
      { name: "Action Verbs", score: 78, type: "ats" },
      { name: "Quantification", score: 74, type: "ats" },
      { name: "Tech Stack", score: 90, type: "ats" },
      { name: "Responsibilities", score: 76, type: "ats" },
      { name: "Certifications", score: 55, type: "ats" },
      { name: "Location", score: 95, type: "ats" },
      { name: "Impact Stories", score: 79, type: "standout" },
      { name: "Uniqueness", score: 68, type: "standout" },
      { name: "Voice Match", score: 75, type: "standout" },
      { name: "Culture Fit", score: 82, type: "standout" },
      { name: "Leadership", score: 65, type: "standout" },
      { name: "Spike Signal", score: 70, type: "standout" },
      { name: "Project Depth", score: 80, type: "standout" },
      { name: "Online Presence", score: 60, type: "standout" },
    ],
  },
  {
    id: "app-3",
    company: "Linear",
    role: "Product Engineer",
    status: "Tailored",
    fitScore: 71,
    callbackPct: 44,
    lastActivity: "3d ago",
    logoInitial: "L",
    jd: `Linear is building the new standard for software project management. We want a Product Engineer who cares deeply about craft, speed, and design.\n\nRequirements:\n- Full-stack experience with React and Node.js\n- Obsession with performance and polish\n- Experience with real-time collaboration features\n- Ability to own features end-to-end`,
    resumeSample: `Mohammed Haarez — Product Engineer\n\nEXPERIENCE\n\nFull-Stack Engineer — Acme Corp (2021–Present)\n• Owned end-to-end delivery of 5 major product features, each used by 100K+ users\n• Reduced bundle size by 45% through code splitting and tree shaking\n• Built collaborative document editor with OT-based conflict resolution`,
    heatmap: [
      { name: "Keyword Match", score: 72, type: "ats" },
      { name: "Skills Alignment", score: 78, type: "ats" },
      { name: "Experience Level", score: 68, type: "ats" },
      { name: "Education Match", score: 75, type: "ats" },
      { name: "Title Match", score: 65, type: "ats" },
      { name: "Recency", score: 85, type: "ats" },
      { name: "Formatting", score: 90, type: "ats" },
      { name: "Length", score: 82, type: "ats" },
      { name: "Action Verbs", score: 76, type: "ats" },
      { name: "Quantification", score: 71, type: "ats" },
      { name: "Tech Stack", score: 80, type: "ats" },
      { name: "Responsibilities", score: 73, type: "ats" },
      { name: "Certifications", score: 50, type: "ats" },
      { name: "Location", score: 95, type: "ats" },
      { name: "Impact Stories", score: 74, type: "standout" },
      { name: "Uniqueness", score: 65, type: "standout" },
      { name: "Voice Match", score: 70, type: "standout" },
      { name: "Culture Fit", score: 76, type: "standout" },
      { name: "Leadership", score: 60, type: "standout" },
      { name: "Spike Signal", score: 67, type: "standout" },
      { name: "Project Depth", score: 75, type: "standout" },
      { name: "Online Presence", score: 58, type: "standout" },
    ],
  },
  {
    id: "app-4",
    company: "Figma",
    role: "Software Engineer, Platform",
    status: "Discovered",
    fitScore: 65,
    callbackPct: 32,
    lastActivity: "5d ago",
    logoInitial: "F",
    jd: `Figma is looking for a Software Engineer for our Platform team to build the infrastructure that powers collaborative design at scale.\n\nRequirements:\n- Strong CS fundamentals\n- Experience with C++, Rust, or WebAssembly preferred\n- Interest in graphics or creative tools\n- Background in high-performance computing`,
    resumeSample: `Mohammed Haarez — Software Engineer\n\nEXPERIENCE\n\nSoftware Engineer — Acme Corp (2021–Present)\n• Optimized rendering pipeline achieving 60fps on mid-tier devices\n• Built plugin system used by 2,000+ third-party developers\n• Contributed to WebAssembly compilation toolchain`,
    heatmap: [
      { name: "Keyword Match", score: 60, type: "ats" },
      { name: "Skills Alignment", score: 65, type: "ats" },
      { name: "Experience Level", score: 70, type: "ats" },
      { name: "Education Match", score: 75, type: "ats" },
      { name: "Title Match", score: 62, type: "ats" },
      { name: "Recency", score: 80, type: "ats" },
      { name: "Formatting", score: 88, type: "ats" },
      { name: "Length", score: 80, type: "ats" },
      { name: "Action Verbs", score: 72, type: "ats" },
      { name: "Quantification", score: 65, type: "ats" },
      { name: "Tech Stack", score: 58, type: "ats" },
      { name: "Responsibilities", score: 68, type: "ats" },
      { name: "Certifications", score: 45, type: "ats" },
      { name: "Location", score: 90, type: "ats" },
      { name: "Impact Stories", score: 68, type: "standout" },
      { name: "Uniqueness", score: 60, type: "standout" },
      { name: "Voice Match", score: 65, type: "standout" },
      { name: "Culture Fit", score: 70, type: "standout" },
      { name: "Leadership", score: 55, type: "standout" },
      { name: "Spike Signal", score: 62, type: "standout" },
      { name: "Project Depth", score: 70, type: "standout" },
      { name: "Online Presence", score: 55, type: "standout" },
    ],
  },
  {
    id: "app-5",
    company: "Notion",
    role: "Backend Engineer",
    status: "Closed",
    fitScore: 55,
    callbackPct: 18,
    lastActivity: "2w ago",
    logoInitial: "N",
    jd: `Notion is building the all-in-one workspace. We need a Backend Engineer to scale our data layer.\n\nRequirements:\n- 4+ years backend experience\n- PostgreSQL and distributed systems expertise\n- Experience with Node.js or Python\n- Interest in collaborative document systems`,
    resumeSample: `Mohammed Haarez — Backend Engineer\n\nEXPERIENCE\n\nBackend Engineer — Acme Corp (2021–Present)\n• Scaled PostgreSQL database from 100GB to 2TB with zero downtime migrations\n• Built event-driven microservices architecture processing 1M events/hour`,
    heatmap: [
      { name: "Keyword Match", score: 55, type: "ats" },
      { name: "Skills Alignment", score: 58, type: "ats" },
      { name: "Experience Level", score: 60, type: "ats" },
      { name: "Education Match", score: 70, type: "ats" },
      { name: "Title Match", score: 58, type: "ats" },
      { name: "Recency", score: 75, type: "ats" },
      { name: "Formatting", score: 85, type: "ats" },
      { name: "Length", score: 78, type: "ats" },
      { name: "Action Verbs", score: 68, type: "ats" },
      { name: "Quantification", score: 60, type: "ats" },
      { name: "Tech Stack", score: 55, type: "ats" },
      { name: "Responsibilities", score: 62, type: "ats" },
      { name: "Certifications", score: 40, type: "ats" },
      { name: "Location", score: 85, type: "ats" },
      { name: "Impact Stories", score: 60, type: "standout" },
      { name: "Uniqueness", score: 52, type: "standout" },
      { name: "Voice Match", score: 58, type: "standout" },
      { name: "Culture Fit", score: 62, type: "standout" },
      { name: "Leadership", score: 48, type: "standout" },
      { name: "Spike Signal", score: 55, type: "standout" },
      { name: "Project Depth", score: 63, type: "standout" },
      { name: "Online Presence", score: 50, type: "standout" },
    ],
  },
];

export interface DemoApproval {
  id: string;
  agentId: string;
  agentName: string;
  summary: string;
  time: string;
}

export const DEMO_APPROVALS: DemoApproval[] = [
  {
    id: "apr-1",
    agentId: "tailor",
    agentName: "Tailor",
    summary: "Resume tailored for Stripe Senior Engineer. ATS score lifted from 61 to 84. 14 bullet points rewritten.",
    time: "2m ago",
  },
  {
    id: "apr-2",
    agentId: "pitcher",
    agentName: "Pitcher",
    summary: "Cover letter drafted for Vercel Staff Engineer role. Voice match 91%. 312 words.",
    time: "18m ago",
  },
  {
    id: "apr-3",
    agentId: "scout",
    agentName: "Scout",
    summary: "12 new roles discovered matching your profile. Top match: Linear Product Engineer (78% fit).",
    time: "1h ago",
  },
];
